### ISSUE TITLE
Responsive theme for mobile phones

### ISSUE THREAD

**Issue by dvogt23** [rust-lang/this-week-in-rust#1017]
Is there a way to make the newsletter content more responsive for mobile phones? I have always to zoom and swipe left/right to read.

**Comment by nasa42** [comment]
This seems to work for me on Gmail app. Which email app do you use and could you please paste a screenshot?

**Comment by dvogt23** [comment]
I use the Mail on my iPhone. Cause of the small I have too zoom...
![B9D999FB-DE0B-4C29-8002-F3C48E6E0AD2](https://user-images.githubusercontent.com/9352647/65684625-59d31a00-e060-11e9-9e9c-be30ecacd979.png)

**Comment by dvogt23** [comment]
Another cool idea would be the new darkmode style for the newsletter theme?

**Comment by dvogt23** [comment]
#1035 I dont know why, but on my iPhone, the font color is grey not white 😑 hows look like in other mail clients?

**Comment by nasa42** [comment]
I use Gmail on Android. Unfortunately I can't test it because [dark theme for Gmail is supported in Android 10](https://gsuiteupdates.googleblog.com/2019/09/dark-theme-android-ios.html), which I at present don't have access to.

**Comment by nellshamrell** [comment]
Closing due to the age of this issue, but if it is still a problem please feel free to open a new issue.
