### ISSUE TITLE
Question: Creation date and category label

### ISSUE THREAD

**Issue by matu3ba** [rust-lang/this-week-in-rust#1235]
Love the series very much.

For general tagging (easier searchability or basic statistics etc) some sort of tagging would be nice.  
Ideally these are machine-readable, but I am unsure what frontend could be used for visualization.

My suggestions for labeling would be 1.Series 2. Pattern, 3. Review, 4. LessonLearned, 5.Experiment, 6.Tool, but any standard way of doing that would be fine.

Date | Tag | Title+Link
| --- | --- | --- |
20200507 | Review | [Async interviews: my take thus far](https://smallcultfollowing.com/babysteps/blog/2020/04/30/async-interviews-my-take-thus-far/)

Otherwise the post date may be hidden on the website view and the items sorted by date.

**Comment by nellshamrell** [comment]
I'm open to something like this, if a community member is willing to implement the tables and test them in the various places people view the site (browsers, email, mobile, etc.). UI/UX development is something my experience is limited in (I have more experience with backend programming), so I would love if this could be done by someone with more expertise in the area.

I wonder if a good compromise for now would be to have a few subsections under news and blog posts, as suggested in #1327

**Comment by nellshamrell** [comment]
We implemented the subsections and it has been working well!
