### ISSUE TITLE
"Call for Blog Posts" closed 05-Oct-2020

### ISSUE THREAD

**Issue by DazWilkin** [rust-lang/this-week-in-rust#1560]
The Rust Blog is no longer accepting blog post submissions (after 05-Oct-2020):

https://github.com/rust-lang/this-week-in-rust/blame/master/draft/2020-10-14-this-week-in-rust.md#L33

**Comment by skade** [comment]
@nellshamrell Not clicking around your bugtracker, but I think this issue can just be closed :).

**Comment by nellshamrell** [comment]
Good point, closing :)
