### ISSUE TITLE
Bounty aggregation?

### ISSUE THREAD

**Issue by ArtemGr** [rust-lang/this-week-in-rust#1660]
I'd like to hear your thoughts (or emojis) on the idea of posting the likes of Bountysource bounties (automatically aggregated) on This Week In Rust?

It's a bit like "Rust Jobs", but also different?
And a bit like "Call for Participation", but also different?

There's also a [small precedent](https://github.com/rust-lang/this-week-in-rust/pull/1445) in using the "Call for Participation" for a bounty?

cf. https://www.reddit.com/r/rust/comments/k17f0k/this_week_in_rust_366/gdxrh6q/

**Comment by programmerjake** [comment]
+1 for having a section for bounties that doesn't disappear after 1 week

**Comment by cdmistman** [comment]
Personally, I'd prefer to remain cautious of bounties being shared on TWiR. I admit to never having done one, but a while back (when I was looking into doing them part-time), I saw a few instances of Bountysource listings where the task was completed but wasn't merged into the bountied repo (thus never satisfying the agreement of the bounty) or the payment was never sent. I think that #1445 is a good template to handle this:

- If somebody would like to include a bounty listing, I think the CfP section is a good candidate
- We won't actively look for bounties - people wishing to increase visibility of a bounty should create their own PR
- The bounty *must* be Rust-related
- An actual bounty must be listed. This implies two things:
  - The bounty should be listed on a recognizable bounty website (Bountysource, ...? - I'm not aware of any others)
  - The payment must be verifiable through a 3rd party (either escrow is available or a recognizable 3rd party can confirm)

Ultimately, I would greatly enjoy more visibility of Rust-related bounties. At the same time, TWiR does adhere to the CoC, so we'd need to make sure we're not hosting unwanted behavior. For example, if a bounty is listed but the payment is never sent, I think that's enough to constitute "baiting"

thoughts? @nellshamrell @llogiq

**Comment by ArtemGr** [comment]
Thanks for the feedback, @cdmistman !
It makes me think of a voting system in the aggregator, allowing the Rust community to vote for issues to be included in TWiR?

**Comment by llogiq** [comment]
I doubt there will be much genuine interest from the community, and we don't have the resources to create a system that cannot easily be gamed. So I don't think voting will buy us much.

On the other hand I'm not directly opposed to including bounties we find newsworthy, but the bar ought to be higher than for regular jobs and we should disclaim affiliation.

**Comment by programmerjake** [comment]
Would NLNet count as a 3rd party for the bounty Libre-SOC is funding via donation from NLNet? Admittedly it is not technically labeled "bounty". This is the "small precedent" linked in the first comment.

**Comment by ArtemGr** [comment]
@llogiq , it grows to be such an interesting discussion, thank you!

> I doubt there will be much genuine interest from the community

It is the chicken and the egg problem, isn't it?
Looking at https://arxiv.org/pdf/1904.02724.pdf I'd say the interest grows when people see the bounty system used successfully and consistenlty in a project. But having no such projects visible in the larger Rust ecosystem yet, we might benefit the tools that would create such visibility, allowing at a glance to see where the bounties are used consistently, whether the bounty is fresh or an afterthought, what bounties has been paid or not paid by that sponsor?

> and we don't have the resources to create a system that cannot easily be gamed

What would you do if we had the tools?
Like, from the abundance mindset maybe?

And can we make shortcuts, like calculating vote power on github Rust commits?

Like in freeism, https://youtu.be/1HJdrBk3BlE, and in the Super Mario Effect, https://youtu.be/9vJRopau0g0, creating a ranking of contribution somehow?
It will not be immediately perfect of course, but what if starting somewhere would then allow us to later improve it?

**Comment by ArtemGr** [comment]
Thanks for the input and eyes!

Looks like the idea of automatically finding Rust bounties and then maybe selecting some good one for TWiR might be a viable one, as I did not see any showstoppers having been mentioned so far.

The open bounty database is something I might be working on at the coming 2021.
Will continue at https://github.com/ArtemGr/bounty/tree/main/notes
