### ISSUE TITLE
Incorrect QotW suggestor in 369

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/this-week-in-rust#1721]
This isn't important, so feel free to not fix and just take a note to watch for it in future.

https://this-week-in-rust.org/blog/2020/12/16/this-week-in-rust-369/#quote-of-the-week says
> Thanks to [Joshua Nelson](https://users.rust-lang.org/t/twir-quote-of-the-week/328/972) for the suggestion.

But that's not the correct URLO link, nor the author of the one who suggested the quotation used.  It should be to https://users.rust-lang.org/t/twir-quote-of-the-week/328/976, not to post 972.

**Comment by llogiq** [comment]
Oops, my bad. I must've inadvertently scrolled between copying the quote and the suggester.

**Comment by scottmcm** [comment]
As I said, not a big deal.  Just something for the proofreader list :)
