### ISSUE TITLE
Please link to reference #921 this week

### ISSUE THREAD

**Issue by Havvy** [rust-lang/this-week-in-rust#1738]
https://github.com/rust-lang/reference/pull/921 is pretty significant and I'd like to see it in TWiR. Not really sure where else to request links.

**Comment by nellshamrell** [comment]
@llogiq, sorry to bring this to your attention so late, do you want to comment on how you select what to include?

**Comment by Havvy** [comment]
I probably should have closed this by now. I'm gonna close it since the actionable item is no longer valid, though I'm not requesting ignoring the previous question.
