### ISSUE TITLE
Add performance triage

### ISSUE THREAD

**Issue by pickfire** [rust-lang/this-week-in-rust#1807]
https://github.com/rust-lang/rustc-perf/blob/master/triage/2021-02-09.md

**Comment by djc** [comment]
Yeah, I noticed that there was no link to the actual triage report either this week or last. Is there a reason for this?

**Comment by nellshamrell** [comment]
No particular reason, it just wasn't included in what was submitted for the performance triage section. If it's included in the PR for that section, I will definitely merge it.
