### ISSUE TITLE
Job opportunity at e.ventures

### ISSUE THREAD

**Issue by njaard** [rust-lang/this-week-in-rust#1824]
Please post a link to my [job post](https://old.reddit.com/r/rust/comments/lhvipu/official_rrust_whos_hiring_thread_for_jobseekers/gn3p99j/) on reddit.

**Comment by nellshamrell** [comment]
Sorry I missed this, in the future could you open up a pull request rather than an issue? Or tag us on Twitter with @thisweekinrust?

**Comment by njaard** [comment]
No problem. I'll open up a pull request. I don't use twitter

**Comment by nellshamrell** [comment]
Thank you!
