### ISSUE TITLE
About recruiting participants for a study on Rust Programmers’ Experience and Challenges

### ISSUE THREAD

**Issue by sfzhu93** [rust-lang/this-week-in-rust#1867]
Hello,

We are a research team from the Pennsylvania State University. We are recruiting participants who are Rust programmers for an online survey study. Participants will earn a $10 Amazon gift card for completing the study. The study will not ask any identification of the participants. After the study, the participants could optionally provide their email address for the gift card. I wonder if we can post a link to our recruitment on TWiR, so that we can recruit more participants. 

My pull request is here:
[](https://github.com/rust-lang/this-week-in-rust/pull/1868
)
But I wonder 1) if there's any requirements for the format/length of the title 2) and where I should put my link. Ideally, I guess we can write a short article about our idea, and attach our survey under "Observations/Thoughts". Otherwise, I think it should be under Papers and Research Projects/Miscellaneous/Call for Participation. Which would be the best valid option?

Thanks in advance.

**Comment by nellshamrell** [comment]
Hello there! I would prefer that your write a short article about the idea (with a link to the survey) that we can include under Papers and Research Projects.

**Comment by sfzhu93** [comment]
Thanks for your reply. I changed my mind - can I put the recruitment link directly on TWiR? Because if we introduce the research project first, the participants may have biases on the survey. I can change my pull request to the appropriate place as you suggested.
