### ISSUE TITLE
Link to "A DSL embedded in Rust" does not work without surveillance

### ISSUE THREAD

**Issue by ijackson** [rust-lang/this-week-in-rust#1978]
Hi.  I was reading https://this-week-in-rust.org/blog/2021/04/28/this-week-in-rust-388/

When I clicked on the link "A DSL embedded in Rust" my browser took me to https://dl.acm.org/action/cookieAbsent

I infer that that link does not work unless I allow the ACM website to track me.  I don't know what This Week in Rust's policy is about this kind of thing, but it seems to me that it should contain only links which work without surveillance.

A web search for the DOI found this: https://kyleheadley.github.io/PHDWebsite/traitlang-IFL18-camready.pdf

Should I send an MR to retrospectively update this link?  Is there something I could usefully do to arrange that this kind of issue is spotted before publication?  (Eg, improve a CI job or something?)

Thanks for your attention.

**Comment by nellshamrell** [comment]
I welcome a merge request to fix the link :)

**Comment by ijackson** [comment]
Your wish is my command :-).
