### ISSUE TITLE
Integration in Discord with Webhooks to get articles

### ISSUE THREAD

**Issue by arn-the-long-beard** [rust-lang/this-week-in-rust#2096]
Hello guys :smiley: 

I read very often your website because I am a **Rust** dude :crab: and **Discord** gave me an idea today so maybe we can discus it.

At my company, we have our Discord server and we are building an environment and a community to grow skills locally and for networking and for spreading our faith in **Rust** :heart: 

I would like to push directly the weekly articles on our server in a specific channel.
So [here ](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks) is the article from Discord about `webhooks`  with an example for Github.  

I was wondering if we could find a solution, and if for you this is valuable or not. Maybe this is too much work for not enough value to make.

What do you think ?  Or is there another solution to get the articles integrated to a Discord channel automatically from your website ?

Best regards,
Arn

**Comment by slyons** [comment]
Could using something like an [RSS Bot](https://github.com/ursineasylum/discord_rss_bot) to monitor the output feeds for changes?

**Comment by bennyvasquez** [comment]
Hi there! I'm going through and reviewing older issues here, and this looks like a great idea! We (the editors) do something similar for community contributions that are gathered by us every week, but don't have any guides for building it at this time. If you go for that, creating a PR like a normal submission would be the best way to submit anything you want to submit. Thanks for being part of the community!
