### ISSUE TITLE
396: 'Rust vs C++ for game development' no longer valid

### ISSUE THREAD

**Issue by Kage-Yami** [rust-lang/this-week-in-rust#2133]
Looks like LogRocket has since deleted their article for 'Rust vs C++ for game development', which is linked in the latest issue of TWiR (396). The link just goes to their blog post listing page, now.

Broken link: https://blog.logrocket.com/rust-vs-c-for-game-development/

(Not on a device amenable to making PRs, so making an issue instead.)

**Comment by andrewpollack** [comment]
Thank you for creating this issue. Presently, we treat newsletters as read-only archived, so we will not remove this broken link
