### ISSUE TITLE
GATs Update

### ISSUE THREAD

**Issue by ibraheemdev** [rust-lang/this-week-in-rust#2134]
[Per jackh726, GATs could be landing on stable as soon as October](https://github.com/rust-lang/rust/issues/44265#issuecomment-869888398). This is of course big news, but I'm not sure where to put it.

**Comment by jackh726** [comment]
I would wait to broadcast this until the blog post comes out after GATs become official not an "incomplete feature"

**Comment by jackh726** [comment]
Btw https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html

**Comment by ibraheemdev** [comment]
Closed by #2259
