### ISSUE TITLE
betterCode Rust (online conference, October 13th)

### ISSUE THREAD

**Issue by badboy** [rust-lang/this-week-in-rust#2228]
There's a new upcoming online conference about Rust: [betterCode Rust](https://rust.bettercode.eu/)

Date: 2021-10-13
Time: 09:00 - 17:00 CEST
Paid conference. Early bird tickets until September 29.

I added it to the community calendar already, but due to it requiring tickets it might be good to have it early in a TWiR.

Note: I'm not associated with the conf, but I know some people in the orga team and was approached by them.

**Comment by nellshamrell** [comment]
We don't generally feature events in the Events section more than two weeks before the event. However, we could feature a link to the conference site in the "Miscellaneous" section. Would you be interested in submitting a pull request for this?

**Comment by badboy** [comment]
Sounds good to me, I'll send a PR in a bit
