### ISSUE TITLE
Feature request: Dark theme for the website

### ISSUE THREAD

**Issue by Walther** [rust-lang/this-week-in-rust#2274]
Thank you for the amazing newsletter 🧡

On the website, it could be nice to have:
- selectable light vs dark mode, with a simple button for picking the active theme, e.g. [dark-mode-toggle](https://github.com/googlechromelabs/dark-mode-toggle) or similar
- possibly autodetect the user-preferred style with `prefers-color-scheme` [css media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) (also supported by above JS snippet and others)
- possibly even support the variety of themes that e.g. `rustdoc` and `mdbook` supports (Light, Rust, Coal, Navy, Ayu)

**Comment by nellshamrell** [comment]
That sounds cool! I'll put a link to this issue in the Call for Participation section of this week's newsletter, perhaps someone from our community can help implement this :)

**Comment by jhpratt** [comment]
Hey @nellshamrell, is this still welcome? I just checked the CSS, and it's quite minimal. I could quite easily add something in with `prefers-color-scheme`.

And looking at the CSS, I actually think a good chunk could be simplified with CSS grid & flexbox. All browsers have supported this for a couple years at least.

**Comment by nellshamrell** [comment]
@jhpratt that would be most welcome!

**Comment by jhpratt** [comment]
Coming back around to this. I see that the theme actually comes from [this repository](https://github.com/Pelican-Elegant/elegant), given the CSS file name. I presume it's fine to just update the CSS in this repo? We'd just have to make sure to maintain the diff if the theme is ever updated.

**Comment by bennyvasquez** [comment]
@jhpratt I'm going through and looking at old issues. Are you still interested in working on this? If not, we'll put out a call for other folks to take a look.

**Comment by jhpratt** [comment]
Interested, yes. But I don't really have time to, as I'm preoccupied with some other things. Feel free to put a call out!

**Comment by flying-sheep** [comment]
Hi, I had this discussion many times.

An important thing to notice is that two-state toggles like the mentioned “dark-mode-toggle” are wholly inadequate, as they don’t allow to select the “auto” mode that makes the most sense on every single major OS: macOS, Linux, or Windows ≥11.

Therefore the only design choices that make sense are:

1. Just derive from `prefers-color-scheme`, no UI. Or:

2. A tri-state UI element that allows to switch between

   - “automatically derive from `prefers-color-scheme`”
   - “user overrides by setting it to light mode”
   - “user overrides by setting it to dark mode”

   Then persist that setting in localstorage or a cookie: `auto`, `light`, or `dark`. Or:

3. The same as 2, but also allow the user to select which light mode theme and dark mode theme to use.

**Comment by flying-sheep** [comment]
In case you go with a button, I think a combination of Furo’s and MkDocs’ behavior is ideal:

- Like Furo, the button should adapt the toggle direction depending on what the system theme currently is, so that the first click always changes the visible theme.
- Like MkDocs, the button should show the current mode, but hovering it should immediately show a tooltip saying ”Switch to […]”

**Comment by GuillaumeGomez** [comment]
Stupid question but why not using mdbook directly? It implements themes and search (which are another feature request).

**Comment by twhiting** [comment]
I'm all for a dark theme FWIW. For those looking for this functionality now try using your browsers built in Reader Mode.
