### ISSUE TITLE
Content quality issues and potential plagiarism in This Week in Rust articles

### ISSUE THREAD

**Issue by JKAnderson409** [rust-lang/this-week-in-rust#2667]
[This article](https://web.archive.org/web/20211202084242/https://blog.knoldus.com/box-pointers-in-rust-make-recursive-types-possible/) was included in today's issue of This Week in Rust. As is common in the content of this newsletter, the article contains identical [code, prose and even an image from The Book](https://doc.rust-lang.org/stable/book/ch15-01-box.html) without attribution, passing the content off as the original work of the author.

Here is an example of prose taken from the book.

The article:

```
A box does not have any capabilities other than storing the data on a heap other than the stack. We use Box in the following cases –

- When you have a type whose size can’t be known at compile time and you want to use a value of that type in a context that requires an exact size
- If you have a large amount of data and you want to transfer ownership but ensure the data won’t be copied when you do so
- When you want to own a value and you care only that it’s a type that implements a particular trait rather than being of a specific type
```

The Book:

```
Boxes don’t have performance overhead, other than storing their data on the heap instead of on the stack. But they don’t have many extra capabilities either. You’ll use them most often in these situations:

- When you have a type whose size can’t be known at compile time and you want to use a value of that type in a context that requires an exact size
- When you have a large amount of data and you want to transfer ownership but ensure the data won’t be copied when you do so
- When you want to own a value and you care only that it’s a type that implements a particular trait rather than being of a specific type
```

The code snippets are just as egregiously identical.

The author has done this multiple times, [here](https://web.archive.org/web/20210922023025/https://blog.knoldus.com/message-passing-in-rust-threads-is-very-helpful/) is an article that mirrors [this](https://doc.rust-lang.org/stable/book/ch16-02-message-passing.html) section of The Book. That article even includes a link to the page from which the content was taken, but does not attribute the content as being identical to the content in the book.

I have tried to identify a contributor to The Book with the same name as this blogger but have not found anyone, just one person with the same first name. Tracing the submission back to the account showed no history of contributing to The Book. If this person's original work is in The Book then this redundancy is an issue of content quality. At worst, this is plagiarism. Low-quality submissions that copy and paste content from authoritative sources have become the norm in this newsletter.

I would prefer to address the issue and see improvements instead of abandoning This Week in Rust for a newsletter that is more prudently moderated (if one exists). I would be happy to look through submissions for content that I recognize from sources I know well (e.g. The Book) but I would like to hear from the team first. If I am mistaken in this example, I would offer an apology for failing to recognize the content as belonging to the author. If I am right in this instance or in any future instance I would like these authors and their domain to be barred from future contributions. I hope I have not wrongly identified this specific article as plagiarism as it is a serious allegation as to the ethical character of the author. I see a great deal of high-quality, high-effort content in this newsletter and I think it's a shame to see it listed alongside low-quality content that often appears to be lifted from elsewhere in the Rust ecosystem.

**Comment by nellshamrell** [comment]
Thank you for bringing this to our attention. We are investigating and evaluating a response.

**Comment by luisvonmuller** [comment]
> The aphorism, “Nothing is lost, nothing is created, everything is transformed,” is attributed to the French chemist Antoine Laurent de Lavoisier, born in 1743.

I dont really think this is actually a problem? The book is open, the knowledge so does. They made something for the community, thats what we should care most.

**Comment by nellshamrell** [comment]
We have investigated this and removed links to content that we confirmed was largely copied (even if some wording was slightly altered) from other sources.

I have also reached out privately to the blog which featured this content clarifying our editorial standards,
