### ISSUE TITLE
low contrast between visited and non-visited links

### ISSUE THREAD

**Issue by Zatnosk** [rust-lang/this-week-in-rust#2688]
The color difference between `a:visited` and `a` links is very small and makes it hard to tell which links are visited.

I'm also unable to see any change in hue, so the color change almost looks like a slight bold-effect, because the color is just a bit darker.

**Comment by bennyvasquez** [comment]
I'm going through and reviewing older issues here, and this is definitely one we see the value of! I've added the 'help wanted' label, and we'll include a reference to this issue in a future edition of TWiR to see if we can get some help with it. Thanks for the feedback!
