### ISSUE TITLE
Check for already present links in PR

### ISSUE THREAD

**Issue by pravic** [rust-lang/this-week-in-rust#2730]
Because often there are duplicated ones in a post.

An example: https://github.com/rust-lang/this-week-in-rust/blob/master/content/2021-12-22-this-week-in-rust.md#observationsthoughts

**Comment by ericseppanen** [comment]
Duplicate of #2378, which is already committed, and will hopefully be run in CI soon.

The duplicates in this week's episode were corrected in #2729.

**Comment by pravic** [comment]
Thanks!
