### ISSUE TITLE
[suggestion] a better way to tackle the duplicate link issue

### ISSUE THREAD

**Issue by hmble** [rust-lang/this-week-in-rust#2780]
In order to check for duplicate link we can use some shell magic like this to check if a link is duplicate or not.

```bash
git diff | awk '/^\+\*/' | grep -Eo '(http|https)://[a-zA-Z0-9./?=_%:-]*' | grep -wof - links.txt
```
Explanation:
1. First we extract newly added link from a diff of PR
2. Check if extracted url already exists in extracted `links.txt`

IMO we can integrate this in CI/CD and add check for PRs. Although the script still isn't correct for scenarios when the contributor adds more than one link and I don't know how to tackle that situation with scripting.

@nellshamrell and @ericseppanen I would like to know your opinion on this.

**Comment by ericseppanen** [comment]
We already have CI for duplicate link checking; see #2768 and `tools/inspect_links.py`.

`links.txt` is manually updated, so it would be hard to handle the case where two PRs collide, which is the most common source of duplicates. I don't think there should be a human-updated file in the loop, when it's possible to extract that information from the original markdown sources.

The current python script also:
- checks that URLs are well-formed
- checks for tracking parameters on links

We can also add new capabilities in the future:
- check that the link appears to work (e.g. not a 404)
- check that the link isn't a redirect (and suggest a canonical form)
- search through old issues, replacing dead links with archived pages
- verify markdown syntax, e.g. catch things that need escaping like `Vec<T, A>`.

**Comment by hmble** [comment]
Yes, this makes sense to me. I knew about `tools/inspect_links.py` thats why I stopped extracting links ( reason mentioned [here](https://github.com/rust-lang/this-week-in-rust/pull/2736#issuecomment-1001021688))

I was just curious to know if this solution is good or not. Thank you for your opinion.

I will try and see if I can help adding new capabilities in exisitng script.
I will close the issue.
