### ISSUE TITLE
Clearer standards for what is and is not included in the Projects section

### ISSUE THREAD

**Issue by nellshamrell** [rust-lang/this-week-in-rust#3119]
There is a lot of variety in what we have historically included in the Project/Tooling Updates section of This Week in Rust. With the abundant growth of Rust projects, it's time to set more specific standards on what we will include, what we will not include, and what we leave to editor judgement.

In our [README](https://github.com/rust-lang/this-week-in-rust/blob/master/README.md), we state [what we are looking for when considering whether to include something in TWiR](https://github.com/rust-lang/this-week-in-rust/blob/master/README.md#what-do-we-look-for-when-considering-whether-to-include-something-in-this-week-in-rust). With regard to Projects/Tooling, we say:

What we are generally looking for includes
* updates on tooling when in long form or framed as a tutorial (for more details, see what we are not looking for below)

What we are generally NOT looking for includes:
* Links to crates or GitHub repos without some sort of context. We would much rather you submit a blog post introducing your project and how a Rust user might use it (and what it would help them do) and/or what you learned about Rust in the process of writing the project.

In the past, I have made exceptions on links to GitHub repos when it is the first time the repo is being featured in TWiR and there is enough context/content in the project README indicated what it is, why it exists, how to use it, and other content that the community can learn from. With Rust's growth, I don't believe this is sustainable anymore and I request input from my fellow editors and community on what the standards for this section should be.

**Comment by joshtriplett** [comment]
FWIW, many projects don't have a blog, and just post a crate with a clear README and perhaps make an announcement on Reddit, internals, users, twitter, etc. This is the approach I tend to take, personally; I don't have a blog and my projects don't tend to either.

I do think it absolutely takes more than just having a "this is crate X which does Y". But if there's detailed information available including guidance on why you might want something and how to use it, and some manner of timely "announcement" material somewhere, perhaps that might suffice?

**Comment by andrewpollack** [comment]
Resolved by https://github.com/rust-lang/this-week-in-rust/pull/3653
