### ISSUE TITLE
new Compiler Performance table does not render on site

### ISSUE THREAD

**Issue by fbstj** [rust-lang/this-week-in-rust#3220]
in [twir #441](https://this-week-in-rust.org/blog/2022/05/04/this-week-in-rust-441/) the "new" compiler performance table introduced recently doe not render as a table.

![image](https://user-images.githubusercontent.com/19763/166888331-8d46a26e-73e4-420d-a0f4-647607b97844.png)

the table was added in #3208

**Comment by ericseppanen** [comment]
Fixed by #3221.
