### ISSUE TITLE
Can I post a Youtube presentation as a "video"? If that's okay, would it be in the Rust Walkthroughs? 

### ISSUE THREAD

**Issue by maximkpa** [rust-lang/this-week-in-rust#3234]

**Comment by ericseppanen** [comment]
Links to YouTube videos are fine. If the video has detailed code examples (showing how to build something in Rust) then it can go in Rust Walkthroughs. Otherwise, it can go in Observations/Thoughts.

**Comment by maximkpa** [comment]
Thank you!!
