### ISSUE TITLE
Scheduled Presentations?

### ISSUE THREAD

**Issue by maximkpa** [rust-lang/this-week-in-rust#3303]
On 8th of June we will host a virtual presentation on Youtube and it fits well "Rust Walkthrough" (its all about Rust).
Can we add the link of a scheduled Youtube video to Rust Walkthrough or to Upcoming events?

**Comment by mariannegoldin** [comment]
Hi there, please feel free to submit a PR with the suggested addition, or if you prefer, share a link here and we can take a look. Thanks for posting.

**Comment by mariannegoldin** [comment]
Hi there, since the event date has passed, closing out this issue. Please feel free to create a new PR with any suggestions for Walkthroughs.
