### ISSUE TITLE
Use Python-Markdown 3.3.7 during site deployment

### ISSUE THREAD

**Issue by ericseppanen** [rust-lang/this-week-in-rust#3338]
We are occasionally bitten by a [bug](https://github.com/Python-Markdown/markdown/issues/1209) in Python-Markdown <= 3.3.6 that causes lines like this:

```
* [add `[T]::as_simd(_mut)`](https://github.com/rust-lang/rust/pull/91479)
```

to be mis-parsed, resulting in a blank line being emitted.

I see that Python-Markdown 3.3.7 has been released, which hopefully has the bugfix. So hopefully we can stop seeing this bug if we can:
1. Force use of Python-Markdown 3.3.7 when deploying the site (@nellshamrell, is this possible?)
2. Force use of Python-Markdown 3.3.7 in CI
3. (optional) remove the workarounds (pointless `&nbsp;` on the end of the troublesome lines)

See #2781, #3336, ade6ded00bf0 for places this bit us in the past.

**Comment by andrewpollack** [comment]
Looking into this now, and using Python-Markdown 3.3.7 on site deploy is absolutely possible. Making the updates now
