### ISSUE TITLE
Rusty Game Jam 2

### ISSUE THREAD

**Issue by ozkriff** [rust-lang/this-week-in-rust#3363]
Hi! Could you mention the announcement of Rusty Game Jam 2 in the next TWIR issue, please? I'm now sure to which section it belongs

https://gamedev.rs/blog/rustyjam-02
https://itch.io/jam/rusty-jam-2

**Comment by ericseppanen** [comment]
Thanks for the links! The first Rusty Jam link is in the latest issue.
