### ISSUE TITLE
Call for Testing of Cargo's -Z sparse-registry

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/this-week-in-rust#3392]
Hi,

It would be lovely to get `-Z sparse-registry` added to the Call for Testing section, this week or next.
internals post: https://internals.rust-lang.org/t/call-for-testing-cargo-sparse-registry/16862
tracking-issue: https://github.com/rust-lang/cargo/issues/9069
rfc: https://rust-lang.github.io/rfcs/2789-sparse-index.html
unstable docs: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#sparse-registry

There will be a blog post on Inside Rust, but it is a race condition if it will be out in time for TWIR. https://github.com/rust-lang/blog.rust-lang.org/pull/990

What are the next steps?

cc @rust-lang/cargo, @arlosi

**Comment by arlosi** [comment]
The blog post is up! https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html

**Comment by Eh2406** [comment]
Tagged the RFC https://github.com/rust-lang/rfcs/pull/2789#issuecomment-1166155551
