### ISSUE TITLE
Dead link in 2022-07-20-this-week-in-rust.md

### ISSUE THREAD

**Issue by punkeel** [rust-lang/this-week-in-rust#3479]
Hi!

Looks like this link is already dead:
https://github.com/rust-lang/this-week-in-rust/blob/29b99ca4436d9436b3d8434a1e5fc3b99bc71baa/content/2022-07-20-this-week-in-rust.md?plain=1#L54=

* [How Rust manages memory using ownership and borrowing](https://stackoverflow.blog/2022/07/14/how-rust-manages-memory-using-ownership-and-borrowing/)

**Comment by andrewpollack** [comment]
Thank you for creating this issue. Presently, we treat newsletters as read-only archived, so we will not remove this dead link
