### ISSUE TITLE
Collaboration with Shuttle

### ISSUE THREAD

**Issue by Saerween** [rust-lang/this-week-in-rust#3616]
Dear This Week in Rust Team,

I'm María from [shuttle](https://shuttle.rs/), the Rust-native cloud development platform.

I'm writing to express our interest in becoming part of your newsletter; could you please provide me with metrics concerning your newsletter along with pricing details, so that we can evaluate it?

Best,

María

**Comment by nellshamrell** [comment]
Hi @Saerween! We keep this as a community run endeavor. We would welcome you and others submit articles, etc to the newsletter :)
