### ISSUE TITLE
Updated Project/Tooling Section Guidelines

### ISSUE THREAD

**Issue by nellshamrell** [rust-lang/this-week-in-rust#3639]
Hello all,

It has been awesome to see the explosive growth in Rust projects across the industry and across (and beyond) our ecosystem. The number of links submitted to the Project/Tooling Updates of TWiR has increased as a result. In order to keep this section as consistently useful to as many members of the Rust community as possible, we are establishing some updated guidelines for submitting links to this section.

We include
* Updates on tooling when in long form or framed as a tutorial (this can be through a blog, through GitHub, through a newsletter, and more) - it must have a high amount of Rust specific info (examples in Rust, notes on things learned about Rust in the process of creating/updating the project, etc.)
* Updates on tooling that call out specific contributors - it is wonderful to highlight all the great people contributing to Rust OSS projects

We do not include
* Updates that are solely a change log without details on the changes, guides to using the changes, etc.
* Links that are solely to a GitHub repo or crate on crates.io. While we would love to include these, there are too many being created/updated every week for us to include them all. We encourage you to write up an introduction to your project with examples, information you learned through creating the project, etc.

Guidelines
* A small description of the project or the update in your link is fine (for example: FooBar 1.0: adding support for Baz)
* We discourage submitting links and link descriptions that are solely of a commercial/sales nature

**Comment by nellshamrell** [comment]
These guidelines will be applied from Issue 460 (which will be published September 15, 2022) forward.

**Comment by U007D** [comment]
> Updates on tooling that call out specific contributors - it is wonderful to highlight all the great people contributing to Rust OSS projects
Could a would-be contributor use attribution as a "pass" for not including Rust-specific info?

**Comment by WeirdConstructor** [comment]
Are they really applied in 462? I am wondering, because I don't know if I should submit the HexoSynth Devlog for the next week (the last one was https://m8geil.de/posts/hexosynth-12/ ). I can't find Rust specific content in the post about gitoxide for instance.

**Comment by andrewpollack** [comment]
Resolved by https://github.com/rust-lang/this-week-in-rust/pull/3653
