### ISSUE TITLE
Add anchors for headers

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/this-week-in-rust#3669]
I was trying to make a link to the `## Final Comment Period` section specifically today, and was surprised that there's no `id`/`name` attributes in the page that could be used for that.

Could the generator be updated to add those?

**Comment by bennyvasquez** [comment]
I'm going through and reviewing older issues here, and this is definitely one we see the value of! I've added the 'help wanted' label, and we'll include a reference to this issue in a future edition of TWiR to see if we can get some help with it. Thanks for the submission!
