### ISSUE TITLE
Update primary branch from `master` to `main`

### ISSUE THREAD

**Issue by FreeMasen** [rust-lang/this-week-in-rust#3764]
In accordance with [Inclusive Naming](https://inclusivenaming.org/word-lists/tier-1/) it would be good to update this community resource to meet that standard. I know that this can be sometimes difficult to manage because of automatons are structured or potential impacts to contribution but it would still be nice to have.

**Comment by bennyvasquez** [comment]
Hi there! Thanks for bringing this up. At the moment we track the rust-lang defaults, but this has sparked a conversation among the editors and may result in us changing sooner. If so, we'll communicate well ahead of time and with a megaphone, for all who would be impacted.
