### ISSUE TITLE
draft/ still has 2022-11-09 but that has been published

### ISSUE THREAD

**Issue by ijackson** [rust-lang/this-week-in-rust#3804]
I wanted to make an MR to add a link to next week's issue.  However, the `master` branch still points to commit `3554b212` which has `draft/2022-11-09-this-week-in-rust.md`, which was published last week.

I also observe that the post-2022-11-09 MR #3803 edits that file, so when this is fixed those changes will have to be re-applied to the new draft.  I guess there may be other post-publication changes to the draft that ought to be transferred.

**Comment by billy1624** [comment]
Yeah, I just want to ask something similar.

**Comment by bennyvasquez** [comment]
We missed that, but the new version has been added as the draft now.

**Comment by billy1624** [comment]
Thanks! @bennyvasquez
