### ISSUE TITLE
Add presence in Telegram

### ISSUE THREAD

**Issue by LumaRay** [rust-lang/this-week-in-rust#3825]
Please consider creating a Telegram group and posting updates in it, maybe using some bot.

**Comment by bennyvasquez** [comment]
Thanks so much for reaching out! We aren't planning to add a Telegram presence at this time, but we are curious: is there a specific reason you're asking for a Telegram option? If there's a need, we might be able to meet it in a different way.

**Comment by LumaRay** [comment]
Thank for the comment! The reason I'm asking about Telegram is that me and (I'm sure) many other people around the world prefer to get news from Telegram rather than email newsletters or Reddit, or specific Rust webpages. So it would be very convenient to have a news digest within a dedicated Telegram group or channel, especially containing news about upcoming Rust events.

**Comment by bennyvasquez** [comment]
Awesome! Thank you very much for that clarification. We'll discuss this with the editors and update you as soon as we can. Please note: there's a holiday this week in the US that will likely delay our response until at least next week.

**Comment by bennyvasquez** [comment]
Hey @LumaRay! We've opted not to take this on right now, as the editors don't currently have the capacity to moderate a group like this. If you end up setting something like this up yourself, feel free to submit a PR for us to include it in a future version of TWiR!
