### ISSUE TITLE
Make dark mode more accessible

### ISSUE THREAD

**Issue by nellshamrell** [rust-lang/this-week-in-rust#4031]
We received [a report in Reddit that the color used for `code` is hard to read against the dark background](https://www.reddit.com/r/rust/comments/10rbkhz/comment/j7d2m3r/?context=3),` especially for people who are color blind. I'd like help with making this more accessible.

**Comment by andrewpollack** [comment]
The theme colors can be found at: https://github.com/rust-lang/this-week-in-rust/blob/master/themes/rusted/static/css/main.scss#L39

Please let us know if any other info is needed; we're excited to help contributors!

**Comment by daalfox** [comment]
I'm a frontend developer, I can help if you want

**Comment by daalfox** [comment]
> Please let us know if any other info is needed; we're excited to help contributors!

help me run this project on local, I'm not really into python

**Comment by daalfox** [comment]
Hi @andrewpollack! Thank you sir, I'll be back with updates soon :)

**Comment by daalfox** [comment]
I'm really sorry I'm busy right now and I don't have any experience on static site generation
I can't work on this :(

**Comment by robbystk** [comment]
I submitted a PR for this which is ready for review at your convenience.

**Comment by andrewpollack** [comment]
> I'm really sorry I'm busy right now and I don't have any experience on static site generation I can't work on this :(

@daalfox No worries! Thank you for taking a look at it

**Comment by andrewpollack** [comment]
@robbystk thank you for the PR! Reviewing now

**Comment by dcormier** [comment]
From the person who originally commented about this on reddit: thank you!
