### ISSUE TITLE
Corrections TWiR #482

### ISSUE THREAD

**Issue by blueglyph** [rust-lang/this-week-in-rust#4066]
Small typo in "Project/Tooling Updates":
- `Nutype - the newtype with gurantees` -> `Nutype - the newtype with guarantees`

In "Rust Walkthroughs":
- `Build and deploy a Wasm smart contract with Rust-based language` -> the actual title is `Astar Tech Talks #6 - Mint WASM NFTs with ink!` ... 🙄 Do you want to keep this link?

**Comment by nellshamrell** [comment]
Fixed the typo.

As for the second link - since the newsletter has already been published and the link does contain Rust content, I am going to leave it in.

Thank you for bringing these to my attention!
