### ISSUE TITLE
TWiR #484, [Video] Generic Traits, Impls, and Slices in Rustlang, wrong URL

### ISSUE THREAD

**Issue by blueglyph** [rust-lang/this-week-in-rust#4113]
The link 

https://www.youtube.com/watch?v=ykQbsTHqKF

should be

https://www.youtube.com/watch?v=ykQbsTHqKFo

I hope it's the right place to report it, since I saw "If you find any errors in this week's issue, please submit a PR." but it links to the pull requests. Let me know which you prefer for next time. 🙂 **EDIT**: Just realized PR could also stand for Pull Request, though I've used it for years as "Problem Report". Forget my silly question.

**Comment by andrewpollack** [comment]
Thank you for raising attention to this! This is fixed by #4114 so I will close this issue to reflect the fix

**Comment by blueglyph** [comment]
For information, it's still the wrong link on the website, maybe the fix was undone by something else?
I suppose that at this point, it doesn't matter anymore though.
