### ISSUE TITLE
Slow homepage response on iOS / iPadOS Safari

### ISSUE THREAD

**Issue by andyeff** [rust-lang/this-week-in-rust#4270]
A lengthy delay in the This Week in Rust homepage becoming interactive on iOS has been observed, on both an iPhone 13 and an iPad (6th-gen).

The delay can be up to 10-11 seconds before the page is fully rendered and links become interactable.

An example screen capture showing this can be found in the embedded video at https://qth.social/@andyf/110209113521888114 (or directly at https://qth.social/system/media_attachments/files/110/209/109/931/381/825/original/e0336127f25696fb.mp4 )

From what I've been able to observe, might it be an issue with a `search-index.st` being sent to the client, which looks to be a 15MB blob, and that the processing of this index is what is blocking a main thread in Safari?

Everything works perfectly on desktop safari and firefox, on both Mac and Windows.

**Comment by andrewpollack** [comment]
Looking into this now, thank you for raising this issue! Indeed slowness is coming from loading the search functionality

To ensure the frontpage experience is smooth across different reading devices, we've temporarily deactivated the search feature (reflected now on the website), and created a followup issue at #4271 . I've confirmed on my end that this has resolved the slowness, but please let us know if the slowness continues on those devices!
