### ISSUE TITLE
Decide where CfP links should go

### ISSUE THREAD

**Issue by ericseppanen** [rust-lang/this-week-in-rust#4336]
When CfP links come in, should they go under the community section? The "Call for Participation" section? The events section?

Also, do we want CfP links to be sticky? (carried over to the next TWiR issue, until the deadline passes, like events?) If they're sticky, we may need to adjust the CI checks, so they don't cause "duplicate link" errors. And maybe the new-issue/template script too?

If we decide to put them in the "Call for Participation" section, we should probably refine the text header, which only talks about project participation, not conferences or other events:
> Always wanted to contribute to open-source projects but did not know where to start?
> Every week we highlight some tasks from the Rust community for you to pick and get started!
> 
> Some of these tasks may also have mentors available, visit the task page for more information.

**Comment by mariannegoldin** [comment]
I would vote for putting the calls for proposals/speakers under the Call for Participation section, as a subheader - Call for Proposals. I would vote for making the calls sticky for up to four issues: this way, they get enough exposure for readers that may have missed them,  but don't appear on repeat for a long period -- some CfPs deadlines are months out.

This is similar to what we do with events (we publish one month out, meaning that events persist over up to four weeks, allowing readers to catch up on upcoming events). 

I would recommend creating a submission mechanism similar to the Calls for Participation submission [thread](https://users.rust-lang.org/t/twir-call-for-participation/4821/70), via the Rust users forum.

**Comment by mariannegoldin** [comment]
Wanted to see if there were any other thoughts on this thread, vis-a-vis a recent [PR](https://github.com/rust-lang/this-week-in-rust/pull/4341/files) to include a CfP in the general Calls section for TWIR 494.

**Comment by bennyvasquez** [comment]
I agree with keeping them in the Call for Participation section. While topically it would make sense to put them with events, this is a type of participation that is very active. Started to add this in [4435](https://github.com/rust-lang/this-week-in-rust/pull/4435)
