### ISSUE TITLE
Meetups asking for an announcement to be included

### ISSUE THREAD

**Issue by badboy** [rust-lang/this-week-in-rust#4391]
The [Rust Meetup in Paris](https://www.eventbrite.fr/e/rust-meetup-in-paris-hosted-by-stockly-tickets-630742055467) (added to the calendar just now) is asking if they can include a call for speakers in the newsletter.

What's the best way to do that? Any section to call this out? Would it be better if they have their own post about it so we can link to it?

**Comment by U007D** [comment]
We could try including a dedicated "Call for Speakers" link under their `Upcoming Events` entry.  Would that work?

**Comment by badboy** [comment]
Oh, I kinda forgot about this. The event happened and they had speakers. Next time I'll send a PR directly adding that section when I know about it.
