### ISSUE TITLE
Consider moving job thread to another place 

### ISSUE THREAD

**Issue by ldicarlo** [rust-lang/this-week-in-rust#4598]
Thank you for this newsletter, and for taking the time to update it.

With the last events regarding Reddit, and considering the awful browser experience there, could we move the job thread (even only temporarily) away from Reddit, to lemmy.world for example? (Or anywhere where the browser experience is better).
Thanks by advance

**Comment by U007D** [comment]
Any thoughts on this, @nellshamrell?

**Comment by nellshamrell** [comment]
We don't have control over where the Reddit job thread lives, but if there is another job thread on a Reddit alternative I'm happy for us to considering including that link as well.

**Comment by ldicarlo** [comment]
Understood. Thanks
