### ISSUE TITLE
Spelling of Auckland in issues #507, #506, #505, and #488

### ISSUE THREAD

**Issue by hdert** [rust-lang/this-week-in-rust#4600]
Kia ora

It seems in issues 506, 505, 488 and future issue 507, the events regarding Rust Auckland seem to have misspelled Auckland as Aukland. I can create a PR to fix the spelling in issue 507 if needed.

Nga mihi nui

Update:
I have opened a PR (#4602) to fix this, for your convenience.

**Comment by andrewpollack** [comment]
Thank you for spotting this! This is an unfortunate typo that was carried over the issues 😿 I've merged the PR for 507, and will keep an eye to make sure the typo does not come up in the future

**Comment by hdert** [comment]
This still seems to be an issue in issues 522 and 523, just so you know!
