### ISSUE TITLE
Finding Duplicates

### ISSUE THREAD

**Issue by c-git** [rust-lang/this-week-in-rust#4608]
When I want to submit a link for some content I find online that I found useful I usually want to check if it's a duplicate before I submit to TWIR but I haven't quite been able to figure out how to do that. Is there an easy way to know if a video for example has already been submitted to TWIR?

**Comment by c-git** [comment]
After I submitted the issue I had this overwhelming feeling of dejavu so I decided to check and found the [response](https://github.com/rust-lang/this-week-in-rust/pull/4098#pullrequestreview-1321247217) from the last time I asked this question (had forgotten that I'd asked). Maybe add a comment in the readme (That's where I looked for advice on how to check for duplicates)?

**Comment by U007D** [comment]
Thoughts on this @mariannegoldin?

**Comment by mariannegoldin** [comment]
Sorry for the delay in replying. 
The best ways to check for duplicates are:
1. Look in the latest draft of TWIR in the `./draft` directory checked in the `master` branch
2. Look at open PRs 

We have a CI pipeline that checks for duplicates, so we do catch these in the editing and publishing process. However, we appreciate your question, as it definitely makes our publishing process smoother if we don't need to address duplicates. However, if you have any corrections to add in a listing, we definitely welcome that.
