### ISSUE TITLE
LWN articles

### ISSUE THREAD

**Issue by Darksonn** [rust-lang/this-week-in-rust#4956]
There are two recent LWN articles on Rust:

 * [Committing to Rust for kernel code](https://lwn.net/Articles/952029/)
 * [A Rust implementation of Android's Binder](https://lwn.net/Articles/953116/)

The first article is already freely available, but the second is still behind a paywall. (They're behind a paywall for ~2 weeks after publication.)

I suggest that you include the first article in the next version of the newsletter, and as for the second article, I would check whether it's still behind a paywall on the release date, and if so, postpone it for the following week.

I didn't submit a PR due to the above timing issues.

**Comment by ojeda** [comment]
+1, please also include [Preventing atomic-context violations in Rust code with klint](https://lwn.net/Articles/951550/) (already freely available too).
