### ISSUE TITLE
Shall rust-playground merge announcements be prefixed?

### ISSUE THREAD

**Issue by vi** [rust-lang/this-week-in-rust#4993]
In [TWiR 526](https://this-week-in-rust.org/blog/2023/12/20/this-week-in-rust-526/) I see:

* [nudge the user to kill programs using excessive CPU](https://github.com/rust-lang/rust-playground/pull/1020)

It looks like a merge that relates to the core Rust language or libraries, but actually deals with the Rust Playground.

Other such merges seems to be prefixed (i.e. "clippy:" or "rust-analyzer:"), but this one stands out.

**Comment by bennyvasquez** [comment]
That's an interesting idea. @llogiq what do you think of this one?

**Comment by llogiq** [comment]
Ok, I will amend that in the future.

**Comment by bennyvasquez** [comment]
Fantastic! Thanks for helping us make TWiR better for everyone, you two!
