### ISSUE TITLE
Next Paris Rust meetup not listed

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/this-week-in-rust#5034]
Next Paris Rust meetup in on the 23rd of January. Page of the event is: https://mobilizon.fr/events/0fce31cd-3578-43f2-abf4-ffecd8d16da2

**Comment by bennyvasquez** [comment]
Hi friend! @mariannegoldin did find the meetup and has added it to the list. You'll see it here this week: https://this-week-in-rust.org/blog/2024/01/10/this-week-in-rust-529/

**Comment by GuillaumeGomez** [comment]
Thanks!
