### ISSUE TITLE
Call-for-testing without an RFC?

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/this-week-in-rust#5222]
Hi! I see the `call-for-testing` label can be applied on the `rust-lang/rfcs` repo to get mentioned in TWiR. I have a feature without an RFC [here](https://github.com/rust-lang/rust/issues/119612#issuecomment-1967092452) that I'd like to get tested. Would it be possible to have a similar label on `rust-lang/rust` issues as well?

**Comment by Urgau** [comment]
cc @U007D

**Comment by U007D** [comment]
Thanks, @Urgau.

@Nadrieril, yes, I can add `Rust|Issues` to the list of places I search each week.  Problem is, I just checked, and I don't have the powers to add the `call-for-testing` label to the `rust` repo, which would enable me to query.  Do you know someone who could do this?

Meanwhile, I will remember to add this issue to CfT next week.

**Comment by Nadrieril** [comment]
Little ping so this makes it into next week's TWiR

**Comment by bennyvasquez** [comment]
Got this added this week in 5282. Thanks @Nadrieril and @U007D!

**Comment by Nadrieril** [comment]
Thank you!

**Comment by rami3l** [comment]
@U007D Following our previous conversation on Reddit, maybe you could add Rustup to the mix? I've made the first issue with the tag, maybe that'd be a good starting point: https://github.com/rust-lang/rustup/issues/3806
