### ISSUE TITLE
Request for Permission to Translate and Publish "This Week In Rust" in Chinese

### ISSUE THREAD

**Issue by daochouwangu** [rust-lang/this-week-in-rust#5238]
Dear This Week In Rust Team,

I hope this message finds you well. My name is Tim Li, and I am a member of [docschina](https://github.com/docschina), a non-profit translation organization dedicated to making valuable technical resources accessible to the Chinese-speaking community.

We have a team of volunteer translators who are passionate about technology and are committed to our mission. Our translations are entirely non-profit, and we do not include any form of advertising in our content. Once translated, we publish the content on our website and our WeChat public account, thereby reaching a large audience in the Chinese-speaking world.

We have already been granted permission to translate and publish newsletters like React Status, JS Weekly, and Node Weekly. These collaborations have been very successful, and we believe that adding This Week In Rust to our repertoire would be immensely beneficial to our readers.

We are reaching out to request your permission to translate and publish the content from This Week In Rust. We assure you that all content will be fully credited to This Week In Rust, and we will provide links to the original content in each of our publications.

We believe this endeavor will not only serve our community but also help promote This Week In Rust to a broader audience.

Thank you for considering our request. We look forward to hearing from you soon.

Best regards,
TimLi
docschina

**Comment by wiktor-k** [comment]
I'm not part of the TWIR team but I'd like to note that https://this-week-in-rust.org/ sites have a footer which links to [CC BY-SA 4.0 DEED](https://creativecommons.org/licenses/by-sa/4.0/) which lists what you can do and I guess translation would be part of the "adapt".

The conditions are exactly what you'd expect: you need to give attribution to the original (but you already said you would do that) but also share your work under the same conditions ("ShareAlike").

I personally think translating is a great idea to reach wider community.

Hope this helps! :wave:

**Comment by daochouwangu** [comment]
Thanks！
