### ISSUE TITLE
Incorrectly nested backquotes in TWIR 537

### ISSUE THREAD

**Issue by oxalica** [rust-lang/this-week-in-rust#5257]
The title of the referenced PR is:
> Never say "`Trait` is implemented for `{type error}`"

But it is actually rendered as: ([here](https://this-week-in-rust.org/blog/2024/03/06/this-week-in-rust-537/#updates-from-the-rust-project))

> never say "`Trait is implemented for` `"`

The backquotes are incorrectly nested in the markdown source.

https://github.com/rust-lang/this-week-in-rust/blob/6e959295e97e9966f1ddfd0e2a2cd4fcbe9ecf5e/content/2024-03-06-this-week-in-rust.md?plain=1#L141

**Comment by bennyvasquez** [comment]
Fixed this when I published 538 this week. Good catch, and thank you!
