### ISSUE TITLE
Add next Rust Paris meetup to agenda

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/this-week-in-rust#5338]
Could you add next Rust Paris meetup to the agenda please (23rd of April)?

Link of the event: https://mobilizon.fr/events/4ba93021-c43a-4e4a-b3e5-09c1c0d0a957

**Comment by ErichDonGubler** [comment]
I'm not a maintainer, but: AIUI this can be managed by an invitation to edit the Rust meetup calendar?

**Comment by GuillaumeGomez** [comment]
That'd be the best long-term solution I think. :+1:

**Comment by mariannegoldin** [comment]
Another suggestion would be to open a PR to add the event - we generally post events from the day of publication to 5 weeks out. But adding it to the calendar is also a great way to ensure it is included. 

I believe that the 23-Apr Paris Rust event has been added to [TWIR 542](https://this-week-in-rust.org/blog/2024/04/10/this-week-in-rust-542/).

**Comment by mariannegoldin** [comment]
This has been resolved, closing the issue.
