### ISSUE TITLE
Update the criteria for inclusion in the CFP section

### ISSUE THREAD

**Issue by bennyvasquez** [rust-lang/this-week-in-rust#5434]
The last time the criteria for the CFP section was stated, far as I can tell, was in 2016 on the forums. I'd like to adjust the requirements, make a post about it on that thread, and then update the guidelines here and make it more obvious, so anyone submitting can be sure what they're required to do. 

[The original criteria](https://users.rust-lang.org/t/twir-call-for-participation/4821)

> * Ensure that your project has at least one open-source licence. (we've decided to not define the term "open-source" and it is left to your own interpretation).
> * Ensure that the issue tracker for your project is publicly accessible.
> * Create a new issue in your issue tracker and clearly describe the task. Also mention the difficulty level (easy/medium/hard/tedious), either as a tag/label or somewhere in the title/description.
> * If you have specific requirements for contributors (e.g., copyright waiver), it must be mentioned in the description of the task (preferably with a link to CONTRIBUTING.md).

I'd like to update it to this:

> * Ensure that your project has at least one [Open Source Initiative-](https://opensource.org/)approved license. 
> * Ensure that the issue tracker for your project is publicly accessible.
> * Create a new issue in your issue tracker and clearly describe the task, and include the difficulty level (easy/medium/hard/tedious), either as a tag/label or somewhere in the title/description.
> * Include a link to your contribution guidelines in the task, and call out any specific requirements for contributors (e.g., copyright waiver).

**Comment by Alodewan576** [comment]
Us
