### ISSUE TITLE
"Call for Testing" is duplicated and misnested

### ISSUE THREAD

**Issue by kpreid** [rust-lang/this-week-in-rust#5443]
In [TWiR 544](https://this-week-in-rust.org/blog/2024/04/24/this-week-in-rust-544/), there are two copies of the (empty) "Call for Testing" section. Additionally, the second copy has heading levels which end up putting the RFC-related headings nested under the second Call for Testing section.

The duplication happened in https://github.com/rust-lang/this-week-in-rust/commit/46055df8d736b1d389d060620bd5466f563da9eb but that commit also added some sub-sections to Call for Testing, so I assume that some of it was intentional (perhaps the section was intended to be moved?); otherwise I'd just send a cleanup PR.

**Comment by bennyvasquez** [comment]
Good catch! I've got #5468 open to potentially fix it. Once that gets reviewed, I'll get it merged in and updated. 

Thanks again!
