### ISSUE TITLE
I'm releasing a game  in Rust--would that be considered relevant?

### ISSUE THREAD

**Issue by MasonRemaley** [rust-lang/this-week-in-rust#5522]
Hey! Long time subscriber, thanks for the great newsletter. :)

I've been developing a game in Rust ([steam page](https://store.steampowered.com/app/1110620/Way_of_Rhea/)) for the last 6 years, and it releases on Monday.

Would it be appropriate for me to make a PR mentioning the release in the newsletter?

**Comment by tbu-** [comment]
I'd say. It doesn't hurt to open a PR anyway.

**Comment by nellshamrell** [comment]
Feel free to open a PR if you haven't already - looks like a super cool game!

**Comment by MasonRemaley** [comment]
Created #5547, thanks! :)
