### ISSUE TITLE
(Question) Old posts

### ISSUE THREAD

**Issue by hardBSDk** [rust-lang/this-week-in-rust#5734]
Do you accept updates released months ago?

I'm asking this because IDK if someone is adding the [Redox OS](https://redox-os.org) updates here, thus I would like to submit the best updates once.

**Comment by bennyvasquez** [comment]
Hi there! We don't accept PRs for previously published posts, only for the content for this week's edition. When you have news to share, please submit it that week to the newsletter, so it can be included!
