### ISSUE TITLE
Oxidize conference videos

### ISSUE THREAD

**Issue by ogoffart** [rust-lang/this-week-in-rust#5735]
The videos from the talks at the Oxidize Conference 2024 were published recently.
Here is the playlist: https://www.youtube.com/playlist?list=PL85XCvVPmGQjRuHYLU83tQPvbXwBXdZMI

I'm making an issue instead of a PR because I don't know if you prefer a single link, or a link to each video like in https://this-week-in-rust.org/blog/2024/06/05/this-week-in-rust-550/#rustnl-2024

**Comment by timClicks** [comment]
A link for each video makes sense for me. This is easiest for the reader.

**Comment by timClicks** [comment]
A playlist for the conference's videos was added to [last week's issue](https://this-week-in-rust.org/blog/2024/07/24/this-week-in-rust-557/).

**Comment by ogoffart** [comment]
closing since it was added in last week's issue.
