### ISSUE TITLE
Accept calls for testing for crates on crates.io?

### ISSUE THREAD

**Issue by joshlf** [rust-lang/this-week-in-rust#5906]
Zerocopy is [preparing to release 0.8](https://github.com/google/zerocopy/discussions/1288), and we'd like to put the call out for people to kick the tires on [our 0.8 alpha release](https://docs.rs/zerocopy/0.8.0-alpha.20/zerocopy/index.html). Would TWiR be open to including crates on crates.io (rather than just RFCs and rust-lang/rust PRs) to the Calls for Testing section? (Or alternatively, adding a separate "calls for testing" section for crates.io)

cc @jswrenn

**Comment by U007D** [comment]
Hi, @joshlf.  @bennyvasquez reached out to me about this.  Given that TWiR is "by Rustaceans for Rustaceans", we think this kind of material from a very well-used crate in our ecosystem is entirely appropriate for the newsletter.

I will include your request in Issue #570 next week, and will add guidelines to our instruction doc on how others (or you in the future) can do this in such a way that I will see your request as I compile the CfT section each week.

Thank you for your valuable contributions and we look forward to bringing some extra attention to your 0.8 alpha release!

**Comment by joshlf** [comment]
Thanks for being accommodating!

The PR that @bennyvasquez was referring to is https://github.com/rust-lang/this-week-in-rust/pull/6007, which is actually different than this issue. We've [already released 0.8](https://crates.io/crates/zerocopy/0.8.6). #6007 is about https://github.com/google/zerocopy/discussions/1802, which is us specifically trying to solicit use cases for a particular feature. Hopefully the same rough logic applies, but it's not exactly the same case.

**Comment by U007D** [comment]
I've added this item and it will appear in TWiR #570.

Note: I decided against documenting how to add such requests for crates in the ecosystem as this request is the first we've received AFAIAA.   Let's wait until there are more before we "standardize" handling of these requests.
